{% set version = '1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stinepack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stinepack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stinepack/stinepack_{{ version }}.tar.gz
  sha256: ada0a8ba0b8d98f7d77cf118b94f6799e25878c4142870bff84b7492df393433

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('stinepack')"           # [not win]
    - "\"%R%\" -e \"library('stinepack')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=stinepack
  license: GPL-2.0-only
  summary: A consistently well behaved method of interpolation based on piecewise rational functions
    using Stineman's algorithm.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
